version: "3.4"

services:
  surapp-api:
    container_name: surapp-api
    build: .
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - surapp_db
    networks:
      - surapp_net

  surapp_db:
    container_name: surapp_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - surapp-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    tty: true
    networks:
      - surapp_net

networks:
  surapp_net:
    external: true

volumes:
  surapp-db-volume:


